### ISSUE TITLE
Error on live mode: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by asonaph** [sleeyax/voltra#12]
**Describe the bug**
The error occurs when test mode is disabled, manifesting after a successful token purchase.

```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5a3b34d]

goroutine 7 [running]:
github.com/sleeyax/voltra/internal/bot.(*Bot).sell(0xc000078690, {0x5c2a0e0, 0xc0001df7c0}, 0xc0000ac360?)
	/github/workspace/internal/bot/bot.go:191 +0x2ed
created by github.com/sleeyax/voltra/internal/bot.(*Bot).Start in goroutine 1
	/github/workspace/internal/bot/bot.go:58 +0x157
```

**Steps to reproduce**
Disabling test mode; it runs normally while in test mode.

`enable_test_mode: false`

Steps:
- I executed `./voltra` in a terminal/command prompt

**Screenshots**
<img width="1394" alt="image" src="https://github.com/sleeyax/voltra/assets/109682776/0a319686-a20c-42ff-a2f2-3cb17685916a">
**System information**
 - OS: `macos`
 - Bot version: latest

**Comment by sleeyax** [comment]
Thank you for reporting this issue. If you can find your way compiling the go source code in this repository I would appreciate an error log of a debug build so I can better pinpoint the exact location of the nil pointer. If not, that's fine though. This needs to be investigated.

**Comment by asonaph** [comment]
<img width="1266" alt="image" src="https://github.com/sleeyax/voltra/assets/109682776/406e6729-3163-4a10-bcee-2c24993ee952">
I am new to Go, so I am trying to run a debug on this code. The problem may occur when boughtCoin.TakeProfit is nil. I am trying to understand and fix it. I will update you soon.

**Comment by sleeyax** [comment]
Thank you for trying to contribute to the project, I appreciate that a lot! I'm here if you need any help or have other questions.
